### ISSUE TITLE
Switch to javascriptcore-sys

### ISSUE THREAD

**Issue by waywardmonkeys** [gtk-rs/javascriptcore-rs#22]
I maintain a `javascriptcore-sys` crate which is more complete and has some documentation.

(I also have a `javascriptcore` crate, but I'm not suggesting replacing this one with it quite yet.)

Getting this crate to use the `javascriptcore-sys` crate is a pretty simple set of changes, and I can submit a PR once PR #21 lands if there's interest in reviewing that.

**Comment by antoyo** [comment]
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Well, it's up to you @antoyo :)

**Comment by antoyo** [comment]
We prefer to have everything in the `gtk-rs` organization.
So, please open PRs to include your contributions.
Thank you.

**Comment by waywardmonkeys** [comment]
JavaScriptCore isn’t a part of gtk, so I don’t see why that needs to be the case. I don’t plan to submit PRs.

**Comment by waywardmonkeys** [comment]
If the concern is actually about making sure there's an active maintainer, I'm more than happy to add other people to the organization that my crates are in.

**Comment by antoyo** [comment]
We prefer to keep everything related to GNOME libraries in the `gtk-rs` organization.
So, I'm closing this issue.
